CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_IDLE_TIMEOUT=8000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000
CONFIG_ZMK_PM_SOFT_OFF=y

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# --- Battery (was Y=50) ---
CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_Y=0
  
# --- Bluetooth icon (was Y=32) ---
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_CUSTOM_X=5
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_CUSTOM_Y=16
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_UNBONDED_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_OUTPUT_BT_UNBONDED_CUSTOM_Y=16

CONFIG_NICE_OLED_WIDGET_PROFILE_TEXT_CUSTOM_X=23
CONFIG_NICE_OLED_WIDGET_PROFILE_TEXT_CUSTOM_Y=18

# --- USB icon (same as BT Y=32) ---
CONFIG_NICE_OLED_WIDGET_OUTPUT_USB_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_OUTPUT_USB_CUSTOM_Y=16

# --- Profile (was Y=137) ---
#HIDDEN, 34 default
CONFIG_NICE_OLED_WIDGET_PROFILE_CUSTOM_X=128 
#HIDDEN, 0 default
CONFIG_NICE_OLED_WIDGET_PROFILE_CUSTOM_Y=32  

# --- Layer (was Y=146) ---
CONFIG_NICE_OLED_WIDGET_LAYER_CUSTOM_X=33
CONFIG_NICE_OLED_WIDGET_LAYER_CUSTOM_Y=12

# --- Modifiers (was Y=100) ---
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_HOR=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_CUSTOM_X=34
CONFIG_NICE_OLED_WIDGET_MODIFIERS_CUSTOM_Y=0

# --- Time ---
CONFIG_NICE_OLED_WIDGET_RAW_HID=y
CONFIG_NICE_OLED_WIDGET_RAW_HID_TIME=y
CONFIG_NICE_OLED_WIDGET_RAW_HID_TIME_CUSTOM_X=68
CONFIG_NICE_OLED_WIDGET_RAW_HID_TIME_CUSTOM_Y=13
CONFIG_NICE_OLED_WIDGET_RAW_HID_TIME_TWO_ROWS=y


# --- Bongo Cat (was Luna X=65) ---
#CONFIG_NICE_OLED_WIDGET_BONGO_CAT_CUSTOM_X=97
#CONFIG_NICE_OLED_WIDGET_BONGO_CAT_CUSTOM_Y=-8
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=n
CONFIG_NICE_OLED_WIDGET_WPM_RAVEN=y
CONFIG_NICE_OLED_WIDGET_RAVEN_CUSTOM_X=95
CONFIG_NICE_OLED_WIDGET_RAVEN_CUSTOM_Y=0

CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_MACOS=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_WINDOWS=y
#CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_BONGO_CAT=y
 
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# Turn on logging, and set ZMK logging to debug output
# CONFIG_ZMK_USB_LOGGING=y
